package sessions

import (
	"os"
	"path/filepath"
	"testing"
)

// Every line below was taken from a real transcript and shortened. The
// point of the table is coverage of shapes rather than of text: a record
// is kept or dropped by its envelope, so one example of each envelope is
// the whole contract.
func TestPromptFrom(t *testing.T) {
	cases := []struct {
		name string
		line string
		want *Prompt // nil means the record is not yours
	}{{
		name: "typed prompt",
		line: `{"type":"user","timestamp":"2026-09-02T09:47:19.000Z","message":{"role":"user","content":"Is the \"session\" software in here?"}}`,
		want: &Prompt{Kind: KindPrompt, Text: `Is the "session" software in here?`},
	}, {
		name: "multi-line prompt keeps its newlines",
		line: `{"type":"user","message":{"content":"line one\nline two"}}`,
		want: &Prompt{Kind: KindPrompt, Text: "line one\nline two"},
	}, {
		name: "slash command with args",
		line: `{"type":"user","message":{"content":"<command-message>loop</command-message>\n<command-name>/loop</command-name>\n<command-args>5m check CI</command-args>"}}`,
		want: &Prompt{Kind: KindSlash, Text: "/loop 5m check CI"},
	}, {
		name: "slash command, name first, no args",
		line: `{"type":"user","message":{"content":"<command-name>/effort</command-name>\n<command-message>effort</command-message>\n<command-args></command-args>"}}`,
		want: &Prompt{Kind: KindSlash, Text: "/effort"},
	}, {
		name: "interrupt marker",
		line: `{"type":"user","message":{"content":[{"type":"text","text":"[Request interrupted by user]"}]}}`,
		want: &Prompt{Kind: KindInterrupt, Text: interrupted},
	}, {
		name: "pasted image beside text",
		line: `{"type":"user","message":{"content":[{"type":"image","source":{}},{"type":"text","text":"Bro, it should look like [Image #1]"}]}}`,
		want: &Prompt{Kind: KindPrompt, Text: "Bro, it should look like [Image #1]", Image: true},
	}, {
		name: "tool result",
		line: `{"type":"user","toolUseResult":{},"message":{"content":[{"type":"tool_result","content":"total 24"}]}}`,
	}, {
		name: "command output",
		line: `{"type":"user","message":{"content":"<local-command-stdout>Set model to Opus 5</local-command-stdout>"}}`,
	}, {
		name: "command caveat",
		line: `{"type":"user","isMeta":true,"message":{"content":"<local-command-caveat>Caveat: generated by the user</local-command-caveat>"}}`,
	}, {
		name: "system reminder",
		line: `{"type":"user","message":{"content":"<system-reminder>As you answer, use this context</system-reminder>"}}`,
	}, {
		name: "task notification",
		line: `{"type":"user","message":{"content":"<task-notification>\n<task-id>wb45376i1</task-id>\n</task-notification>"}}`,
	}, {
		name: "skill body injected as meta",
		line: `{"type":"user","isMeta":true,"message":{"content":[{"type":"text","text":"Base directory for this skill: /home/x/.claude/skills/foo"}]}}`,
	}, {
		name: "subagent turn",
		line: `{"type":"user","isSidechain":true,"message":{"content":"Search the repo for foldFile"}}`,
	}, {
		name: "compact summary",
		line: `{"type":"user","isCompactSummary":true,"message":{"content":"This session is being continued from..."}}`,
	}, {
		name: "assistant turn",
		line: `{"type":"assistant","message":{"content":[{"type":"text","text":"Yes. sessions/ is a Go CLI"}]}}`,
	}, {
		name: "malformed json",
		line: `{"type":"user","message":{"content":`,
	}}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, ok := promptFrom([]byte(c.line))
			if c.want == nil {
				if ok {
					t.Fatalf("kept a record that is not a prompt: %+v", got)
				}
				return
			}
			if !ok {
				t.Fatal("dropped a prompt")
			}
			if got.Kind != c.want.Kind {
				t.Errorf("kind = %q, want %q", got.Kind, c.want.Kind)
			}
			if got.Text != c.want.Text {
				t.Errorf("text = %q, want %q", got.Text, c.want.Text)
			}
			if got.Image != c.want.Image {
				t.Errorf("image = %v, want %v", got.Image, c.want.Image)
			}
		})
	}
}

// A prompt that opens with "<" is the documented cost of telling envelopes
// apart by shape. The test exists so the day it matters, the failure is a
// decision on record rather than a surprise.
func TestPromptFromDropsPromptOpeningWithATag(t *testing.T) {
	line := `{"type":"user","message":{"content":"<html> tags in my prompt are lost"}}`
	if _, ok := promptFrom([]byte(line)); ok {
		t.Fatal("a prompt opening with < is now kept — update the doc comment on fromString")
	}
}

func TestPromptReaderReadsOnlyWhatIsNew(t *testing.T) {
	path := filepath.Join(t.TempDir(), "transcript.jsonl")
	write := func(s string) {
		t.Helper()
		f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o600)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := f.WriteString(s); err != nil {
			t.Fatal(err)
		}
		f.Close()
	}
	user := func(text string) string {
		return `{"type":"user","message":{"content":"` + text + `"}}` + "\n"
	}

	write(user("first") + `{"type":"assistant","message":{"content":[]}}` + "\n" + user("second"))

	r := NewPromptReader(path)
	got, err := r.Next()
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 2 {
		t.Fatalf("first read got %d prompts, want 2", len(got))
	}
	if got[0].N != 1 || got[1].N != 2 {
		t.Errorf("numbering = %d,%d, want 1,2", got[0].N, got[1].N)
	}

	// Nothing appended: nothing returned. A follow loop ticks far more often
	// than a prompt arrives, so this is the common case, not an edge one.
	if got, err := r.Next(); err != nil || len(got) != 0 {
		t.Fatalf("idle read got %d prompts (err %v), want 0", len(got), err)
	}

	// A live session is mid-write. The partial line must not be parsed, and
	// must not be skipped either — it is a prompt that has not landed yet.
	write(`{"type":"user","message":{"content":"thi`)
	if got, err := r.Next(); err != nil || len(got) != 0 {
		t.Fatalf("partial-line read got %d prompts (err %v), want 0", len(got), err)
	}

	write(`rd"}}` + "\n")
	got, err = r.Next()
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 {
		t.Fatalf("completed-line read got %d prompts, want 1", len(got))
	}
	if got[0].Text != "third" {
		t.Errorf("text = %q, want %q", got[0].Text, "third")
	}
	if got[0].N != 3 {
		t.Errorf("numbering restarted: N = %d, want 3", got[0].N)
	}
}
